version: "3"
services:
  notebook:
    hostname: notebook-server
    ports:
      - "8888:8888"
      - "4040:4040"
    stdin_open: true
    tty: true
    volumes:
      - ./work:/home/jovyan/work
    build: .
