version: "3"
services:
  notebook:
    hostname: notebook-server
    ports:
      - "8888:8888"
      - "4040:4040"
    links:
      - mysql
    stdin_open: true
    tty: true
    volumes:
      - ./work:/home/jovyan/work
    build: .
    networks:
      - web

  mysql:
    image: "mysql:latest"
    hostname: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      web:
        aliases:
          - mysql-server

networks:
  web:
    driver: bridge
