version: "3"
services:
  notebook:
    ports:
      - "8888:8888"
      - "4040:4040"
    links:
      - mysql
    stdin_open: true
    tty: true
    volumes:
      - ./work:/home/jovyan/work
    build: .
    
  mysql:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: password
    #ports:
    #  - "27017:27017"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
